### ISSUE TITLE
Wrong offset after upload pause

### ISSUE THREAD

**Issue by Retenodus** [dirkmoors/drf-tus#1]
Hello,

Using tus-js, I tried to upload a "big" file (like 630Mo), with a chunk size of ~100485760 bytes. During the upload, I have closed my browser.

Expected behaviour : the file is partially written into /tmp, the Upload-Offset field is set at the number of bytes actually written.

Actual behaviour : the file is partially written into /tmp, the Upload-Offset field is set at the number of chunks processed times the size of a chunk.

In my tests, I have stopped the upload during the third chunk. I have 100485760*2+67813376 = 268784896 bytes written on the filesystem whereas my Upload-Length in database is 100485760*3 = 301457280 bytes.

In django settings I have configured:
FILE_UPLOAD_MAX_MEMORY_SIZE = 162144000
DATA_UPLOAD_MAX_MEMORY_SIZE = None

I tried to track down the issue and it seems that the issue lies in the models.py file:

`    def write_data(self, bytes, chunk_size):
        write_bytes_to_file(self.temporary_file_path, self.upload_offset, bytes, makedirs=True)

        self.upload_offset += chunk_size
        self.save()
`
Here, the chunk_size assumes that the chunk is totally uploaded. In my tests, it looks like I get the correct upload_offset value using len(bytes) whereas than chunk_size for the update for upload_offset but I don't know if that could cause other issues, or if I missed something.

Is there any reason to not use len(bytes) ?

Regards,
Grégoire

**Comment by dirkmoors** [comment]
@Retenodus Could you propose (and test) a patch for this behavior?

**Comment by dirkmoors** [comment]
@Retenodus This should be fixed now:
https://github.com/dirkmoors/drf-tus/pull/7

If the issue still occurs, please reopen this ticket or create a new one.
